/**
 * 생산·활동·고용 지표. docs/metrics.pdf 1절 중 "실물 경제의 규모"와 고용에 해당한다.
 * 판정 기준(watch)은 docs/spec/macro-metrics.md에서 정한 것을 옮겼다.
 */
import type { MacroMetric } from './types';

export const ACTIVITY_METRICS: MacroMetric[] = [
  {
    id: 'gdp',
    group: 'real-economy',
    label: '실질 GDP',
    source: 'fred',
    seriesId: 'GDPC1',
    transform: 'yoy',
    frequency: 'Q',
    unit: '%',
    watch:
      '한 나라가 실제로 생산한 양. 전분기 대비 연율이 두 분기 연속 마이너스면 침체로 확정한다. 다만 발표가 늦어서 이미 벌어진 일을 확인하는 값이지, 앞을 내다보는 값은 아니다.',
    linkedTo: ['payrolls', 'retail-sales'],
  },
  {
    id: 'indpro',
    group: 'real-economy',
    label: '산업생산',
    source: 'fred',
    seriesId: 'INDPRO',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '공장·광산·발전소가 실제로 만들어 낸 양. GDP보다 한 달 단위로 빨리 나와서 경기가 꺾이는 시점을 먼저 보여준다.',
    linkedTo: ['tcu', 'capex', 'gdp'],
  },
  {
    id: 'tcu',
    group: 'real-economy',
    label: '설비가동률',
    source: 'fred',
    seriesId: 'TCU',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '가진 설비 중 실제로 돌리고 있는 비율. 80%를 넘으면 설비가 모자라 증설 투자가 나오고, 낮으면 물가 압력도 함께 식는다.',
    linkedTo: ['indpro', 'capex'],
  },
  {
    id: 'cfnai',
    group: 'real-economy',
    label: '시카고 연준 활동지수',
    source: 'fred',
    seriesId: 'CFNAI',
    transform: 'level',
    frequency: 'M',
    unit: '지수',
    watch:
      '시카고 연준이 85개 지표를 하나로 합친 활동 지수. 0이 평균 성장이고, 3개월 평균이 −0.7을 밑돌면 침체 진입 신호로 본다.',
    linkedTo: ['gdp', 'indpro', 'payrolls'],
  },
  {
    id: 'durable-orders',
    group: 'real-economy',
    label: '내구재 주문',
    source: 'fred',
    seriesId: 'DGORDER',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '자동차·기계처럼 오래 쓰는 물건의 신규 주문액. 기업과 가계가 큰돈 쓸 결심을 하고 있는지 보여주는 값이라 경기에 앞선다.',
    linkedTo: ['capex', 'indpro'],
  },
  {
    id: 'construction',
    group: 'real-economy',
    label: '건설지출',
    source: 'fred',
    seriesId: 'TTLCONS',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '민간과 정부가 건설에 실제로 쓴 돈. 금리에 민감해서 인상 사이클에서 가장 먼저 식고 인하 사이클에서 먼저 살아난다.',
    linkedTo: ['houst', 'capex'],
  },
  {
    id: 'inventories',
    group: 'real-economy',
    label: '기업 재고',
    source: 'fred',
    seriesId: 'BUSINV',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '기업이 쌓아 둔 재고. 매출보다 재고가 빨리 늘면 안 팔려 쌓이는 것이라, 곧 생산을 줄이고 고용도 손댄다.',
    linkedTo: ['retail-sales', 'indpro'],
  },
  {
    id: 'empire-fed',
    group: 'real-economy',
    label: '엠파이어 제조업 서베이',
    source: 'fred',
    seriesId: 'GACDISA066MSFRBNY',
    transform: 'level',
    frequency: 'M',
    unit: '지수',
    watch:
      '뉴욕 연준이 매달 초 제조업체에 직접 물어 만든 체감 지수. 0보다 크면 확장, 작으면 위축이다. 공식 통계보다 한 달 빠르다.',
    linkedTo: ['philly-fed', 'indpro'],
  },
  {
    id: 'philly-fed',
    group: 'real-economy',
    label: '필라델피아 제조업 서베이',
    source: 'fred',
    seriesId: 'GACDFSA066MSFRBPHI',
    transform: 'level',
    frequency: 'M',
    unit: '지수',
    watch:
      '필라델피아 연준의 같은 형식 제조업 서베이. 엠파이어와 같은 방향이면 신호가 단단하고, 엇갈리면 아직 판단하기 이르다.',
    linkedTo: ['empire-fed', 'indpro'],
  },
  {
    id: 'payrolls',
    group: 'real-economy',
    label: '비농업 고용',
    source: 'fred',
    seriesId: 'PAYEMS',
    transform: 'diff',
    frequency: 'M',
    unit: '천 명',
    watch:
      '한 달 동안 늘어난 일자리 수. 최근 3개월 평균이 10만 명을 밑돌면 고용이 식고 있다는 뜻이고, 침체 국면에서는 금리 인하를 기대하는 근거가 된다.',
    linkedTo: ['unemployment', 'claims', 'effr'],
  },
  {
    id: 'unemployment',
    group: 'real-economy',
    label: '실업률',
    source: 'fred',
    seriesId: 'UNRATE',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '일자리를 찾는 사람 중 못 구한 비율. 최근 3개월 평균이 지난 1년 중 가장 낮았던 때보다 0.5%p 넘게 높아지면(삼 룰) 침체에 들어섰다고 본다.',
    linkedTo: ['payrolls', 'claims'],
  },
  {
    id: 'u6',
    group: 'real-economy',
    label: '광의 실업률(U-6)',
    source: 'fred',
    seriesId: 'U6RATE',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '실업자에 더해, 일자리를 포기했거나 원치 않게 단시간만 일하는 사람까지 넣은 넓은 실업률. 공식 실업률과 격차가 벌어지면 겉보기보다 나쁘다.',
    linkedTo: ['unemployment', 'participation'],
  },
  {
    id: 'participation',
    group: 'real-economy',
    label: '경제활동참가율',
    source: 'fred',
    seriesId: 'CIVPART',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '일할 나이대 중 일하거나 일자리를 찾고 있는 사람의 비율. 이 값이 떨어지면서 실업률이 낮아진 것은 좋아진 게 아니라 구직을 포기한 것이다.',
    linkedTo: ['unemployment', 'u6'],
  },
  {
    id: 'claims',
    group: 'real-economy',
    label: '신규 실업수당 청구',
    source: 'fred',
    seriesId: 'ICSA',
    transform: 'level',
    frequency: 'W',
    unit: '건',
    watch:
      '실업수당을 새로 신청한 사람 수. 매주 나와서 고용 지표 중 가장 빠르다. 4주 평균이 26만 건을 넘어서면 고용이 나빠지기 시작한 것으로 본다.',
    linkedTo: ['payrolls', 'unemployment'],
  },
  {
    id: 'continued-claims',
    group: 'real-economy',
    label: '계속 실업수당 청구',
    source: 'fred',
    seriesId: 'CCSA',
    transform: 'level',
    frequency: 'W',
    unit: '건',
    watch:
      '실업수당을 계속 받고 있는 사람 수. 신규 청구가 새로 잘린 사람이라면 이 값은 다시 취업하지 못하고 있는 사람이라, 늘면 재취업이 어려워진 것이다.',
    linkedTo: ['claims', 'unemployment'],
  },
  {
    id: 'job-openings',
    group: 'real-economy',
    label: '구인 건수',
    source: 'fred',
    seriesId: 'JTSJOL',
    transform: 'level',
    frequency: 'M',
    unit: '천 명',
    watch:
      '기업이 사람을 구하고 있는 자리 수. 실업자 수와 비교해 이 값이 크면 노동시장이 빡빡해 임금이 오르고, 줄어들면 먼저 식는 신호다.',
    linkedTo: ['payrolls', 'quits', 'unemployment'],
  },
  {
    id: 'quits',
    group: 'real-economy',
    label: '자발적 이직률',
    source: 'fred',
    seriesId: 'JTSQUR',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '스스로 회사를 그만둔 사람의 비율. 더 좋은 자리로 옮길 자신이 있을 때 오르므로, 노동자가 느끼는 체감 경기를 가장 솔직하게 보여준다.',
    linkedTo: ['job-openings', 'wages'],
  },
  {
    id: 'layoffs',
    group: 'real-economy',
    label: '해고 건수',
    source: 'fred',
    seriesId: 'JTSLDL',
    transform: 'level',
    frequency: 'M',
    unit: '천 명',
    watch:
      '해고·정리해고로 일자리를 잃은 사람 수. 신규 실업수당 청구와 함께 오르기 시작하면 고용 악화가 진짜로 시작된 것이다.',
    linkedTo: ['claims', 'payrolls'],
  },
  {
    id: 'work-hours',
    group: 'real-economy',
    label: '주당 근로시간',
    source: 'fred',
    seriesId: 'AWHAETP',
    transform: 'level',
    frequency: 'M',
    unit: '시간',
    watch:
      '민간 근로자의 주당 평균 노동시간. 기업은 사람을 자르기 전에 근무시간부터 줄이므로, 고용 지표 중 가장 먼저 꺾인다.',
    linkedTo: ['payrolls', 'layoffs'],
  },
  {
    id: 'wages',
    group: 'real-economy',
    label: '시간당 임금',
    source: 'fred',
    seriesId: 'CES0500000003',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '시간당 평균 임금이 1년 전보다 오른 폭. 4%를 넘게 오르면 서비스 물가를 밀어 올려 연준이 인하를 미루는 근거가 된다.',
    linkedTo: ['core-pce', 'quits', 'payrolls'],
  },
];
