/**
 * 물가·소비·주택 지표. docs/metrics.pdf 1절 중 "물가 및 고용 지표"와 소비 쪽이다.
 * 판정 기준(watch)은 docs/spec/macro-metrics.md에서 정한 것을 옮겼다.
 */
import type { MacroMetric } from './types';

export const PRICE_METRICS: MacroMetric[] = [
  {
    id: 'cpi',
    group: 'real-economy',
    label: 'CPI',
    source: 'fred',
    seriesId: 'CPIAUCSL',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '소비자가 사는 물건값이 1년 전보다 얼마나 올랐는지. 3%를 넘어 다시 오름폭이 커지면 연준이 금리를 올릴 명분이 생기고, 2%대에 안착하면 내릴 여지가 생긴다.',
    linkedTo: ['core-pce', 'effr', 'wti'],
  },
  {
    id: 'core-cpi',
    group: 'real-economy',
    label: '근원 CPI',
    source: 'fred',
    seriesId: 'CPILFESL',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '값이 심하게 출렁이는 식품·에너지를 뺀 물가. 유가가 내려서 전체 물가가 떨어져도 이 값이 3%대에서 안 내려오면 금리 인하는 미뤄진다.',
    linkedTo: ['cpi', 'core-pce'],
  },
  {
    id: 'core-pce',
    group: 'real-economy',
    label: '근원 PCE',
    source: 'fred',
    seriesId: 'PCEPILFE',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '연준이 2% 목표를 잴 때 쓰는 공식 물가 지표. CPI와 서로 다른 방향을 가리킬 때 연준은 이쪽을 따르므로, 둘이 갈리면 이 값이 기준이다.',
    linkedTo: ['cpi', 'effr'],
  },
  {
    id: 'ppi',
    group: 'real-economy',
    label: 'PPI(최종수요)',
    source: 'fred',
    seriesId: 'PPIFIS',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '기업이 물건을 넘길 때 받는 가격. 소비자 물가보다 한두 달 앞서 움직여서, 이 값이 먼저 꺾이면 물가가 잡히기 시작했다는 초기 신호다.',
    linkedTo: ['cpi', 'wti'],
  },
  {
    id: 'cpi-food',
    group: 'real-economy',
    label: '식료품 물가(밥상 물가)',
    source: 'fred',
    seriesId: 'CPIUFDSL',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '장을 볼 때 바로 체감하는 식료품 물가. 전체 물가가 내려도 이 값이 높으면 소비가 먼저 줄고, 물가를 잡으라는 정치권 압박도 여기서 나온다.',
    linkedTo: ['cpi', 'retail-sales', 'politics'],
  },
  {
    id: 'shelter-cpi',
    group: 'real-economy',
    label: '주거비 물가',
    source: 'fred',
    seriesId: 'CPIHOSSL',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '집세와 자가주거비를 담은 주거비 물가. CPI에서 가장 비중이 크고 가장 늦게 움직여서, 여기가 안 내려오면 전체 물가도 안 내려온다.',
    linkedTo: ['cpi', 'home-prices'],
  },
  {
    id: 'inflation-expect-1y',
    group: 'real-economy',
    label: '기대 인플레이션 1년(가계)',
    source: 'fred',
    seriesId: 'MICH',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '가계가 직접 답한 향후 1년 물가 예상. 시장이 매긴 기대와 달리 주유소 기름값에 크게 흔들려서, 소비 심리와 함께 움직인다.',
    linkedTo: ['sentiment', 'cpi'],
  },
  {
    id: 'inflation-expect-5y',
    group: 'real-economy',
    label: '기대 인플레이션 5년',
    source: 'fred',
    seriesId: 'T5YIE',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '채권 시장이 값으로 매긴 향후 5년 평균 물가 예상(기대인플레이션). 실제 물가보다 연준이 더 신경 쓰는 값이라, 여기가 흔들리면 정책이 강해진다.',
    linkedTo: ['inflation-expect-10y', 'core-pce'],
  },
  {
    id: 'inflation-expect-10y',
    group: 'real-economy',
    label: '기대 인플레이션 10년',
    source: 'fred',
    seriesId: 'T10YIE',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '같은 방식으로 계산한 향후 10년 물가 예상. 장기 기대가 2%대에 붙어 있으면 연준은 단기 물가가 튀어도 버틸 수 있다.',
    linkedTo: ['inflation-expect-5y', 'dgs10'],
  },
  {
    id: 'inflation-expect-5y5y',
    group: 'real-economy',
    label: '기대 인플레이션 5년 후 5년',
    source: 'fred',
    seriesId: 'T5YIFR',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '5년 뒤부터 그다음 5년간의 물가 예상. 지금의 유가·환율 충격을 걷어낸 값이라, 연준이 물가 기대가 풀렸는지 볼 때 이 값을 본다.',
    linkedTo: ['inflation-expect-5y', 'inflation-expect-10y'],
  },
  {
    id: 'retail-sales',
    group: 'real-economy',
    label: '소매판매',
    source: 'fred',
    seriesId: 'RSAFS',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '소비자가 실제로 쓴 돈. 물가가 오르면 금액은 저절로 늘어나므로, 증가율이 물가 상승률보다 낮으면 실질 소비는 오히려 줄고 있는 것이다.',
    linkedTo: ['cpi', 'gdp'],
  },
  {
    id: 'real-consumption',
    group: 'real-economy',
    label: '실질 소비지출',
    source: 'fred',
    seriesId: 'PCEC96',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '물가 상승분을 걷어낸 실제 소비량. 미국 GDP의 3분의 2가 소비라, 이 값이 마이너스로 가면 성장도 따라 내려간다.',
    linkedTo: ['retail-sales', 'real-income', 'gdp'],
  },
  {
    id: 'real-income',
    group: 'real-economy',
    label: '실질 가처분소득',
    source: 'fred',
    seriesId: 'DSPIC96',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '세금을 내고 물가를 걷어낸 뒤 손에 남는 실질 소득. 소득이 안 느는데 소비만 늘고 있다면 저축을 헐거나 빚을 내고 있다는 뜻이다.',
    linkedTo: ['real-consumption', 'savings-rate'],
  },
  {
    id: 'savings-rate',
    group: 'real-economy',
    label: '저축률',
    source: 'fred',
    seriesId: 'PSAVERT',
    transform: 'level',
    frequency: 'M',
    unit: '%',
    watch:
      '가처분 소득 중 쓰지 않고 남긴 비율. 팬데믹 이후 쌓였던 여윳돈이 바닥나면 이 값이 낮아지면서 소비가 버티기 어려워진다.',
    linkedTo: ['real-income', 'revolving-credit'],
  },
  {
    id: 'revolving-credit',
    group: 'real-economy',
    label: '신용카드 대출 잔액',
    source: 'fred',
    seriesId: 'REVOLSL',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '신용카드처럼 돌려 막는 소비자 대출 잔액. 소득이 정체된 상태에서 이 값만 빠르게 늘면 소비가 빚으로 버티고 있다는 신호다.',
    linkedTo: ['savings-rate', 'real-consumption'],
  },
  {
    id: 'vehicle-sales',
    group: 'real-economy',
    label: '자동차 판매',
    source: 'fred',
    seriesId: 'TOTALSA',
    transform: 'level',
    frequency: 'M',
    unit: '백만 대',
    watch:
      '연율로 환산한 자동차 판매 대수. 대출로 사는 물건이라 금리에 민감하고, 큰 지출을 미루기 시작하는 시점을 잘 잡아낸다.',
    linkedTo: ['durable-orders', 'real-consumption'],
  },
  {
    id: 'sentiment',
    group: 'real-economy',
    label: '소비자 심리',
    source: 'fred',
    seriesId: 'UMCSENT',
    transform: 'level',
    frequency: 'M',
    unit: '지수',
    watch:
      '미시간대가 가계에 물어 만든 소비 심리 지수. 실제 소비보다 물가와 주가에 민감하게 반응해서, 체감이 꺾이는 시점을 먼저 보여준다.',
    linkedTo: ['retail-sales', 'inflation-expect-1y'],
  },
  {
    id: 'houst',
    group: 'real-economy',
    label: '주택 착공',
    source: 'fred',
    seriesId: 'HOUST',
    transform: 'level',
    frequency: 'M',
    unit: '천 호',
    watch:
      '새로 착공한 주택 수(연율). 착공은 앞으로 몇 달간의 건설 고용과 자재 수요로 이어져서 경기에 앞선다.',
    linkedTo: ['permit', 'mortgage-rate', 'construction'],
  },
  {
    id: 'permit',
    group: 'real-economy',
    label: '건축 허가',
    source: 'fred',
    seriesId: 'PERMIT',
    transform: 'level',
    frequency: 'M',
    unit: '천 호',
    watch:
      '건축 허가를 받은 주택 수. 착공보다 한 단계 앞선 값이라, 허가가 먼저 꺾이면 몇 달 뒤 착공도 따라 꺾인다.',
    linkedTo: ['houst', 'mortgage-rate'],
  },
  {
    id: 'new-home-sales',
    group: 'real-economy',
    label: '신규 주택 판매',
    source: 'fred',
    seriesId: 'HSN1F',
    transform: 'level',
    frequency: 'M',
    unit: '천 호',
    watch:
      '새로 지은 단독주택의 판매 건수(연율). 건설사가 값을 깎아서라도 파는 국면인지, 수요가 살아 있는지를 가른다.',
    linkedTo: ['existing-home-sales', 'mortgage-rate'],
  },
  {
    id: 'existing-home-sales',
    group: 'real-economy',
    label: '기존 주택 판매',
    source: 'fred',
    seriesId: 'EXHOSLUSM495S',
    transform: 'level',
    frequency: 'M',
    unit: '호',
    watch:
      '기존 주택 거래 건수(연율). 시장 전체 거래의 대부분을 차지하며, 낮은 금리로 묶인 집주인들이 안 내놓으면 거래가 마른다.',
    linkedTo: ['new-home-sales', 'mortgage-rate'],
  },
  {
    id: 'home-prices',
    group: 'real-economy',
    label: '주택 가격(케이스-실러)',
    source: 'fred',
    seriesId: 'CSUSHPINSA',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '케이스-실러 전국 주택가격 지수의 1년 상승률. 주거비 물가에 1년 남짓 시차를 두고 반영돼서, 여기가 꺾이면 나중에 CPI가 내려온다.',
    linkedTo: ['existing-home-sales', 'cpi'],
  },
  {
    id: 'mortgage-rate',
    group: 'real-economy',
    label: '30년 주택담보대출 금리',
    source: 'fred',
    seriesId: 'MORTGAGE30US',
    transform: 'level',
    frequency: 'W',
    unit: '%',
    watch:
      '30년 고정 주택담보대출 평균 금리. 10년 국채 금리를 따라 움직이며, 7%를 넘으면 실수요자가 사실상 시장에서 밀려난다.',
    linkedTo: ['dgs10', 'houst', 'existing-home-sales'],
  },
];
