/**
 * 채권·환율·지정학 지표. docs/metrics.pdf 4~6절. 앞의 조건들에 시장이 어떻게 반응하는지를 본다.
 * 판정 기준(watch)은 docs/spec/macro-metrics.md에서 정한 것을 옮겼다.
 */
import type { MacroMetric } from './types';

export const MARKET_METRICS: MacroMetric[] = [
  {
    id: 'dgs3m',
    group: 'bond',
    label: '미 국채 3개월',
    source: 'fred',
    seriesId: 'DGS3MO',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '3개월 국채 금리. 사실상 현재 정책금리를 그대로 비추는 값이라, 정책금리보다 낮아지면 시장이 곧 인하를 확신한다는 뜻이다.',
    linkedTo: ['effr', 't10y3m'],
  },
  {
    id: 'dgs2',
    group: 'bond',
    label: '미 국채 2년',
    source: 'fred',
    seriesId: 'DGS2',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '2년 만기 국채 금리. 앞으로 2년간의 정책금리 예상을 압축한 값이다. 급락하면 인하 기대라기보다 실물 경제가 무너지고 있다는 신호일 수 있다.',
    linkedTo: ['effr', 'fedwatch', 't10y2y'],
  },
  {
    id: 'dgs5',
    group: 'bond',
    label: '미 국채 5년',
    source: 'yahoo',
    seriesId: '^FVX',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '5년 국채 금리. 정책 기대(2년)와 성장·물가 전망(10년)의 중간에 있어서, 커브 전체가 어떤 모양으로 움직이는지 볼 때 기준점이 된다.',
    linkedTo: ['dgs2', 'dgs10'],
  },
  {
    id: 'dgs10',
    group: 'bond',
    label: '미 국채 10년',
    source: 'yahoo',
    seriesId: '^TNX',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '10년 만기 국채 금리. 물가 전망과 국채 발행 물량에 함께 반응한다. 물가는 그대로인데 금리만 오르면 발행이 많아 시장이 소화하지 못한다는 뜻으로 읽는다.',
    linkedTo: ['t10y2y', 'bill-share', 'dxy'],
  },
  {
    id: 'dgs30',
    group: 'bond',
    label: '미 국채 30년',
    source: 'yahoo',
    seriesId: '^TYX',
    transform: 'level',
    frequency: 'D',
    unit: '%',
    watch:
      '30년 국채 금리. 정책보다 재정 부담과 장기 물가를 반영해서, 여기만 튀어 오르면 나라 빚에 대한 시장의 불안으로 읽는다.',
    linkedTo: ['dgs10', 'bill-share'],
  },
  {
    id: 't10y2y',
    group: 'bond',
    label: '10년-2년 금리차',
    source: 'fred',
    seriesId: 'T10Y2Y',
    transform: 'level',
    frequency: 'D',
    unit: '%p',
    watch:
      '10년 금리에서 2년 금리를 뺀 값. 마이너스(역전)면 침체 경고인데, 역전이 풀리는 방식이 더 중요하다. 2년이 급락해서 풀리면 실물이 무너지는 신호이고, 10년이 급등해서 풀리면 재정·물가 문제다.',
    linkedTo: ['dgs2', 'dgs10', 't10y3m'],
  },
  {
    id: 't10y3m',
    group: 'bond',
    label: '10년-3개월 금리차',
    source: 'fred',
    seriesId: 'T10Y3M',
    transform: 'level',
    frequency: 'D',
    unit: '%p',
    watch:
      '10년 금리에서 3개월 금리를 뺀 값. 연준이 침체 확률을 계산할 때 쓰는 조합이다. 10년-2년보다 늦게 역전되고 늦게 풀린다.',
    linkedTo: ['t10y2y', 'effr'],
  },
  {
    id: 'hy-oas',
    group: 'bond',
    label: '하이일드 가산금리',
    source: 'fred',
    seriesId: 'BAMLH0A0HYM2',
    transform: 'level',
    frequency: 'D',
    unit: '%p',
    watch:
      '신용등급이 낮은 기업이 국채보다 얼마나 높은 금리를 물고 돈을 빌리는지. 4%p를 넘어 계속 벌어지면 돈줄이 막히는 중이다. 주식보다 먼저 무너지는 자리라 위험 신호로 쓴다.',
    linkedTo: ['ig-oas', 'dealer-capacity', 'capex'],
  },
  {
    id: 'ig-oas',
    group: 'bond',
    label: '우량 회사채 가산금리',
    source: 'fred',
    seriesId: 'BAMLC0A0CM',
    transform: 'level',
    frequency: 'D',
    unit: '%p',
    watch:
      '우량 기업이 국채보다 더 물어야 하는 금리. 좁게 유지되면 기업이 싸게 돈을 빌릴 수 있다는 뜻이라, 회사채를 찍어 설비에 투자하기 좋은 국면이다.',
    linkedTo: ['hy-oas', 'capex', 'dgs10'],
  },
  {
    id: 'capex',
    group: 'bond',
    label: '핵심 자본재 수주',
    source: 'fred',
    seriesId: 'NEWORDER',
    transform: 'yoy',
    frequency: 'M',
    unit: '%',
    watch:
      '기업이 앞으로 들여올 설비를 주문한 금액(항공기·국방 제외). 돈 빌리기 좋아진 여건이 실제 투자로 이어지고 있는지 확인하는 자리다.',
    linkedTo: ['ig-oas', 'gdp', 'power'],
  },
  {
    id: 'dxy',
    group: 'trade-fx',
    label: '달러 인덱스(DXY)',
    source: 'yahoo',
    seriesId: 'DX-Y.NYB',
    transform: 'level',
    frequency: 'D',
    unit: '지수',
    watch:
      '주요 통화 대비 달러의 값. 달러가 약해지면 미국 수출에 유리하고 신흥국으로 돈이 돌아오기 쉬워진다. 상단 티커와 같은 심볼이며, 더 넓은 통화 바스켓이 필요하면 FRED의 DTWEXBGS를 쓴다.',
    linkedTo: ['usdjpy', 'usdkrw', 'dgs10'],
  },
  {
    id: 'usdjpy',
    group: 'trade-fx',
    label: '달러/엔',
    source: 'yahoo',
    seriesId: 'JPY=X',
    transform: 'level',
    frequency: 'D',
    unit: '엔',
    watch:
      '1달러가 몇 엔인지. 엔이 강해지면 싼 엔화를 빌려 다른 자산에 넣어 둔 돈이 청산되면서 위험자산이 함께 흔들린다.',
    linkedTo: ['dxy', 'usdkrw'],
  },
  {
    id: 'usdkrw',
    group: 'trade-fx',
    label: '달러/원',
    source: 'yahoo',
    seriesId: 'KRW=X',
    transform: 'level',
    frequency: 'D',
    unit: '원',
    watch: '1달러가 몇 원인지. 원화가 강세로 돌아서야 외국인 자금이 국내 시장으로 들어온다.',
    linkedTo: ['dxy', 'usdjpy'],
  },
  {
    id: 'trade-balance',
    group: 'trade-fx',
    label: '무역수지',
    source: 'fred',
    seriesId: 'BOPGSTB',
    transform: 'level',
    frequency: 'M',
    unit: '백만 달러',
    watch:
      '수출에서 수입을 뺀 월간 금액. 분기로 나오는 순수출이 어느 쪽으로 갈지 한 달 먼저 알려준다.',
    linkedTo: ['net-exports', 'dxy'],
  },
  {
    id: 'net-exports',
    group: 'trade-fx',
    label: '순수출(GDP 기여)',
    source: 'fred',
    seriesId: 'NETEXP',
    transform: 'level',
    frequency: 'Q',
    unit: '십억 달러',
    watch:
      '수출입이 성장에 얼마나 보탰는지(분기). 성장의 어느 만큼이 해외 수요에서 나왔는지 보여준다.',
    linkedTo: ['trade-balance', 'gdp', 'ai-exports'],
  },
  {
    id: 'wti',
    group: 'geopolitics',
    label: 'WTI 유가',
    source: 'yahoo',
    seriesId: 'CL=F',
    transform: 'level',
    frequency: 'D',
    unit: '달러',
    watch:
      '미국산 원유 가격. 지정학 충돌이 물가로 번지는 통로다. 급등하면 생산자물가에서 소비자물가로 이어지는 경로를 다시 계산해야 한다.',
    linkedTo: ['brent', 'cpi', 'ppi', 'geo-risk'],
  },
  {
    id: 'brent',
    group: 'geopolitics',
    label: '브렌트 유가',
    source: 'yahoo',
    seriesId: 'BZ=F',
    transform: 'level',
    frequency: 'D',
    unit: '달러',
    watch:
      '북해산 원유 가격. WTI와의 차이가 벌어지면 공급 차질이 미국 밖에서 벌어지고 있다는 뜻이다.',
    linkedTo: ['wti', 'geo-risk'],
  },
];
